version: "3"
services:
  vendor-portal:
    image: sangram1989/selenium-docker
    environment:
    - BROWSER=chrome
    - HUB_HOST=hub    
    - THREAD_COUNT=3
    - TEST_SUITE=testng.xml
    volumes:
    - ./output/vendor-portal:/home/selenium-docker/test-output
  flight-reservation:
    image: sangram1989/selenium-docker
    environment:
    - BROWSER=firefox
    - HUB_HOST=hub    
    - THREAD_COUNT=4
    - TEST_SUITE=testng.xml
    volumes:
    - ./output/Vendor-portal:/home/selenium-docker/test-output