services:
  hub:
    image: seleniarm/hub:4.20
  chrome:
    image: seleniarm/node-chromium:4.20
    shm_size: '2g'
    depends_on:
      - hub
#    deploy:
#      replicas: 10
    environment:
      - SE_EVENT_BUS_HOST=hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
      - SE_NODE_MAX_SESSIONS=4
      - SE_VNC_NO_PASSWORD=1
  firefox:
    image: seleniarm/node-firefox:4.20
    shm_size: '2g'
    depends_on:
      - hub
#    deploy:
#      replicas: 10
    environment:
      - SE_EVENT_BUS_HOST=hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
      - SE_NODE_MAX_SESSIONS=4
      - SE_VNC_NO_PASSWORD=1
  vendor-portal:
    image: sangram1989/selenium-docker
    depends_on:
      - chrome
    environment:
      - BROWSER=chrome
      - HUB_HOST=hub
      - THREAD_COUNT=4
      - TEST_SUITE=testng.xml
    volumes:
      - ./output/Vendor-portal:/home/selenium-docker/test-output
